#ifndef SCRIPT_RESOURSES_H
#define SCRIPT_RESOURSES_H

SCRIPT script_library[] = {
    SCRIPT("Grasrrow",ANIMATION_ARROW,FOREGROUND_GREEN,SCRIPT_ARROW,1,0,1,1,0),
    SCRIPT("Protomater",ANIMATION_BEAM,FOREGROUND_RED,SCRIPT_BEAM,2,0,1,1,0),
    SCRIPT("-1/12",ANIMATION_WAVE,BACKGROUND_WHITE,SCRIPT_WAVE,1,0,2,1,10),
    SCRIPT("Double coin",ANIMATION_AURA,FOREGROUND_BLUE | FOREGROUND_INTENSITY,SCRIPT_WAVE,1,0,1,2,1),
    SCRIPT("Try",ANIMATION_AURA,BACKGROUND_WHITE,SCRIPT_WAVE,1,0,0,3,1),
    SCRIPT("One more try",ANIMATION_AURA,FOREGROUND_RED | FOREGROUND_INTENSITY,SCRIPT_WAVE,1,0,1,2,1),
    SCRIPT("RESH",ANIMATION_BEAM,FOREGROUND_BLUE | FOREGROUND_INTENSITY,SCRIPT_BEAM,3,0,2,1,1),
    SCRIPT("MAEBMAEB",ANIMATION_BEAM,BACKGROUND_GREEN | FOREGROUND_INTENSITY,SCRIPT_BEAM,1,1,1,1,1),
    SCRIPT("FACEISDAPLACE",ANIMATION_WAVE,BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,SCRIPT_WAVE,10,1,4,1,2),
    SCRIPT("fluctuating memories",ANIMATION_WAVE,BACKGROUND_BLUE | FOREGROUND_BLUE,SCRIPT_WAVE,10,0,10,1,100),
    SCRIPT("Wrath fo Leah",ANIMATION_WAVE,BACKGROUND_RED,SCRIPT_WAVE,1,0,10,1,10),
    SCRIPT("Hell fork",ANIMATION_SPAWN,BACKGROUND_RED | FOREGROUND_RED | FOREGROUND_INTENSITY,SCRIPT_SPAWN,1,CREATURE_STAMP("Evil fork",1,2,1,1,INTELLECT_HELPER,{},'F',0)),
    SCRIPT("Hell spoon",ANIMATION_SPAWN,BACKGROUND_RED | FOREGROUND_RED | FOREGROUND_INTENSITY,SCRIPT_SPAWN,1,CREATURE_STAMP("Evil spoon",2,1,2,1,INTELLECT_HELPER,{},'S',0)),
    SCRIPT("Hell air",ANIMATION_BEAM,BACKGROUND_RED | FOREGROUND_RED | FOREGROUND_INTENSITY,SCRIPT_BEAM,0,1,1,10,1),
    SCRIPT()
};


#endif // SCRIPT_RESOURSES_H
